version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bmlambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mu574teebbb"
s3_prefix = "bmlambda"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
